apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dozzle
  namespace: base-infrastructure
spec:
  selector:
    matchLabels:
      app: dozzle
  template:
    metadata:
      labels:
        app: dozzle
    spec:
      serviceAccountName: dozzle
      containers:
      - name: dozzle
        image: amir20/dozzle:latest
        ports:
        - containerPort: 8080
        env:
        - name: DOZZLE_LEVEL
          value: "info"
        - name: DOZZLE_TAILSIZE
          value: "300"
        volumeMounts:
        - name: varlog
          mountPath: /var/log
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dozzle
  namespace: base-infrastructure

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dozzle
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dozzle
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dozzle
subjects:
- kind: ServiceAccount
  name: dozzle
  namespace: base-infrastructure

---
apiVersion: v1
kind: Service
metadata:
  name: dozzle
  namespace: base-infrastructure
spec:
  selector:
    app: dozzle
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP