version: "3.9"

services:
  postgresql:
    image: postgres
    container_name: postgresql

    restart: always

    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - postgresql-network
    env_file:
      - ../stack.env
    volumes:
      - /root/containers/postgresql/docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d
      - /root/containers/postgresql/data:/var/lib/postgresql/

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin

    restart: always

    networks:
      - postgresql-network
      - caddy-network

    env_file:
      - ../stack.env

    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - /root/containers/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgresql

volumes:
  postgresql:
    name: postgresql

networks:
  postgresql-network:
    external: true
    name: postgresql-network
  caddy-network:
    external: true
    name: caddy-network
