apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: base-infrastructure-ingress
  namespace: base-infrastructure
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"  # If using cert-manager
spec:
  tls:
  - hosts:
    - git.arcbjorn.com
    - analytics.arcbjorn.com
    - uptime.arcbjorn.com
    - server.arcbjorn.com
    - logs.arcbjorn.com
    - memos.arcbjorn.com
    - k8s.arcbjorn.com
    secretName: arcbjorn-tls
  rules:
  
  # Git Repository Hosting
  - host: git.arcbjorn.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gitea
            port:
              number: 3000
  
  # Analytics Dashboard
  - host: analytics.arcbjorn.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: umami
            port:
              number: 3000
  
  # Uptime Monitoring
  - host: uptime.arcbjorn.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: uptime-kuma
            port:
              number: 3001
  
  # File Browser (Filestash)
  - host: server.arcbjorn.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: filebrowser
            port:
              number: 8080
  
  # Container Logs Viewer
  - host: logs.arcbjorn.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dozzle
            port:
              number: 8080
  
  # Notes and Memos
  - host: memos.arcbjorn.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: memos
            port:
              number: 5230