version: "3"

services:
  umami:
    image: ghcr.io/mikecao/umami:postgresql-latest
    container_name: umami
    env_file:
      - ../stack.env
    depends_on:
      - umami_db

    ports:
      - "{UMAMI_PORT}:3000"
    networks:
      - caddy-network
    restart: always

  umami_db:
    image: postgres:12-alpine
    container_name: umami_db

    env_file:
      - ../stack.env
    volumes:
      - /containers/umami/schema.postgresql.sql:/docker-entrypoint-initdb.d/schema.postgresql.sql:ro
      - /containers/umami/db:/var/lib/postgresql/data
    restart: always

volumes:
  umami-db-data:

networks:
  caddy-network:
    external: true
    name: caddy-network
