version: "3.3"

services:
  filebrowser:
    image: hurlenko/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    environment:
      - FB_BASEURL=/
    volumes:
      - /:/data
      - /root/containers/filebrowser/config:/config
    networks:
      - caddy-network
    ports:
      - 8081:8080 # <Host Port>:<Container Port>

networks:
  caddy-network:
    external: true
    name: caddy-network
