apiVersion: v1
kind: ServiceAccount
metadata:
  name: tailscale
  namespace: base-infra
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tailscale
  namespace: base-infra
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "update", "create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tailscale
  namespace: base-infra
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tailscale
subjects:
- kind: ServiceAccount
  name: tailscale
  namespace: base-infra