apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: base-infrastructure
spec:
  selector:
    app: postgresql
  ports:
  - port: 5432
    targetPort: 5432
    name: postgresql
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-headless
  namespace: base-infrastructure
spec:
  selector:
    app: postgresql
  ports:
  - port: 5432
    targetPort: 5432
    name: postgresql
  clusterIP: None