apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-init-scripts
  namespace: base-infrastructure
data:
  create-multiple-postgresql-databases.sh: |
    #!/bin/bash

    set -e
    set -u

    echo "Starting database initialization script"
    echo "POSTGRES_MULTIPLE_DATABASES: $POSTGRES_MULTIPLE_DATABASES"

    function create_user_and_database() {
        local database=$1
        local user=$2
        local password=$3
        echo "  Creating user '$user' and database '$database'"
        psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
            SELECT 'Creating user and database: $database' as status;
            CREATE USER "$user" WITH PASSWORD '$password';
            CREATE DATABASE "$database" OWNER "$user";
            GRANT ALL PRIVILEGES ON DATABASE "$database" TO "$user";
EOSQL
        echo "  Granting schema permissions for $database"
        psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$database" <<-EOSQL
            GRANT ALL PRIVILEGES ON SCHEMA public TO "$user";
            GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "$user";
            GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO "$user";
EOSQL
    }

    if [ -n "$POSTGRES_MULTIPLE_DATABASES" ]; then
        echo "Multiple database creation requested: $POSTGRES_MULTIPLE_DATABASES"
        # Format: db:user:password,db:user:password
        for db_config in $(echo $POSTGRES_MULTIPLE_DATABASES | tr ',' ' '); do
            database=$(echo $db_config | cut -d':' -f1)
            user=$(echo $db_config | cut -d':' -f2) 
            password=$(echo $db_config | cut -d':' -f3)
            create_user_and_database $database $user $password
        done
        echo "Multiple databases created successfully"
        
        # List created databases and users
        psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -c "\l"
        psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -c "\du"
    else
        echo "No multiple databases configured"
    fi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: base-infrastructure
data:
  # PostgreSQL Configuration
  POSTGRES_PORT: "5432"
  
  # Umami Configuration  
  UMAMI_PORT: "3000"