apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: base-infra
type: Opaque
data:
  # PostgreSQL Main User (must be 'postgres' for initialization)
  POSTGRES_USER: cG9zdGdyZXM=     # postgres
  POSTGRES_PASSWORD: PLACEHOLDER_POSTGRES_PASSWORD
  POSTGRES_DB: cG9zdGdyZXM=       # postgres
  # Database creation (format: db:user:password,db:user:password)
  # Example: gitea:gitea:gitea,umami:umami:umami,dokploy:dokploy:dokploy
  POSTGRES_MULTIPLE_DATABASES: PLACEHOLDER_MULTIPLE_DATABASES

  # Individual Gitea Database Keys (required by gitea-deployment.yaml)
  GIT_DB: PLACEHOLDER_GITEA_DB_NAME
  GIT_DB_USER: PLACEHOLDER_GITEA_DB_USER  
  GIT_DB_USER_PASSWORD: PLACEHOLDER_GITEA_DB_PASSWORD

  # Application Database URLs
  UMAMI_DATABASE_URL: PLACEHOLDER_UMAMI_DATABASE_URL
  DOKPLOY_DATABASE_URL: PLACEHOLDER_DOKPLOY_DATABASE_URL
  GITEA_RUNNER_REGISTRATION_TOKEN: PLACEHOLDER_GITEA_RUNNER_REGISTRATION_TOKEN

---
# Instructions for deployment:
# 1. Copy to server: scp secrets-actual.yaml root@167.235.67.6:~/base_infrastructure/k8s/namespace/secrets.yaml
# 2. Apply on server: kubectl apply -f k8s/namespace/secrets.yaml