apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: base-infra
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: MjIwNTk2
  POSTGRES_DB: cG9zdGdyZXM=
  POSTGRES_MULTIPLE_DATABASES: Z2l0ZWE6Z2l0ZWE6Z2l0ZWEsdW1hbWk6dW1hbWk6dW1hbWk=
  GIT_DB: Z2l0ZWE=
  GIT_DB_USER: Z2l0ZWE=
  GIT_DB_USER_PASSWORD: Z2l0ZWE=
  UMAMI_DATABASE_URL: cG9zdGdyZXM6Ly91bWFtaTp1bWFtaUBwb3N0Z3Jlc3FsOjU0MzIvdW1hbWk=

---
# Instructions for deployment:
# 1. Copy to server: scp secrets-actual.yaml root@167.235.67.6:~/base_infrastructure/k8s/namespace/secrets.yaml
# 2. Apply on server: kubectl apply -f k8s/namespace/secrets.yaml