apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: base-infra
type: Opaque
data:
  # PostgreSQL Main User (must be 'postgres' for initialization)
  POSTGRES_USER: cG9zdGdyZXM=     # postgres
  POSTGRES_PASSWORD: PLACEHOLDER_POSTGRES_PASSWORD
  POSTGRES_DB: cG9zdGdyZXM=       # postgres
  
  # Database creation (format: db:user:password,db:user:password)
  POSTGRES_MULTIPLE_DATABASES: PLACEHOLDER_MULTIPLE_DATABASES
  
  # Individual Gitea Database Keys (required by gitea-deployment.yaml)
  GIT_DB: PLACEHOLDER_GITEA_DB_NAME
  GIT_DB_USER: PLACEHOLDER_GITEA_DB_USER  
  GIT_DB_USER_PASSWORD: PLACEHOLDER_GITEA_DB_PASSWORD
  
  # Application Database URLs  
  GITEA_DATABASE_URL: PLACEHOLDER_GITEA_DATABASE_URL
  UMAMI_DATABASE_URL: PLACEHOLDER_UMAMI_DATABASE_URL

---
# Instructions for updating secrets:
# 1. Base64 encode your actual values: echo -n "your-value" | base64
# 2. Replace the placeholder values above
# 3. Apply: kubectl apply -f secrets.yaml