apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: base-infrastructure
type: Opaque
data:
  # PostgreSQL Secrets (base64 encoded)
  # Replace these with your actual base64-encoded values from stack.env
  POSTGRES_USER: cG9zdGdyZXM=     # postgres
  POSTGRES_PASSWORD: Y2hhbmdlbWU=  # changeme  
  POSTGRES_DB: cG9zdGdyZXM=       # postgres
  POSTGRES_MULTIPLE_DATABASES: ""  # your multiple DB config
  
  # Umami Database Secrets (uses shared PostgreSQL)
  UMAMI_DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3JlczpjaGFuZ2VtZUBwb3N0Z3Jlc3FsOjU0MzIvdW1hbWk=  # postgres://postgres:changeme@postgresql:5432/umami
  
  # Gitea Database Secrets
  GIT_DB: Z2l0ZWE=                 # gitea
  GIT_DB_USER: Z2l0ZWE=            # gitea
  GIT_DB_USER_PASSWORD: Y2hhbmdlbWU=  # changeme

---
# Instructions for updating secrets:
# 1. Base64 encode your actual values: echo -n "your-value" | base64
# 2. Replace the placeholder values above
# 3. Apply: kubectl apply -f secrets.yaml