apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: base-infrastructure
type: Opaque
data:
  # PostgreSQL Main User
  POSTGRES_USER: cG9zdGdyZXM=     # postgres
  POSTGRES_PASSWORD: Y2hhbmdlbWU=  # changeme
  POSTGRES_DB: cG9zdGdyZXM=       # postgres
  
  # Database creation (format: db:user:password,db:user:password)
  POSTGRES_MULTIPLE_DATABASES: Z2l0ZWE6Z2l0ZWE6Z2l0ZWEsdW1hbWk6dW1hbWk6dW1hbWk=  # gitea:gitea:gitea,umami:umami:umami
  
  # Application Database URLs  
  GITEA_DATABASE_URL: cG9zdGdyZXM6Ly9naXRlYTpnaXRlYUBwb3N0Z3Jlc3FsOjU0MzIvZ2l0ZWE=  # postgres://gitea:gitea@postgresql:5432/gitea
  UMAMI_DATABASE_URL: cG9zdGdyZXM6Ly91bWFtaTp1bWFtaUBwb3N0Z3Jlc3FsOjU0MzIvdW1hbWk=  # postgres://umami:umami@postgresql:5432/umami

---
# Instructions for updating secrets:
# 1. Base64 encode your actual values: echo -n "your-value" | base64
# 2. Replace the placeholder values above
# 3. Apply: kubectl apply -f secrets.yaml